spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/madpaatoppen
    username: chef
    password: hungry

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

server:
  port: 8081
